-- Clínica Veterinária
-- PostgreSQL
-- Criação das tabelas

CREATE TABLE IF NOT EXISTS pessoas (
    id_pessoa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    email VARCHAR(150) UNIQUE,
    telefone VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS clientes (
    id_pessoa BIGINT PRIMARY KEY,
    CONSTRAINT fk_clientes_pessoas
        FOREIGN KEY (id_pessoa)
        REFERENCES pessoas(id_pessoa)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS atendentes (
    id_pessoa BIGINT PRIMARY KEY,
    CONSTRAINT fk_atendentes_pessoas
        FOREIGN KEY (id_pessoa)
        REFERENCES pessoas(id_pessoa)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS veterinarios (
    id_pessoa BIGINT PRIMARY KEY,
    crmv VARCHAR(30) NOT NULL UNIQUE,
    especialidade VARCHAR(100) NOT NULL,
    CONSTRAINT fk_veterinarios_pessoas
        FOREIGN KEY (id_pessoa)
        REFERENCES pessoas(id_pessoa)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS animais (
    id_animal BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    especie_classe VARCHAR(80) NOT NULL,
    sexo VARCHAR(20) NOT NULL,
    data_nascimento DATE NOT NULL,
    id_cliente BIGINT NOT NULL,
    CONSTRAINT fk_animais_clientes
        FOREIGN KEY (id_cliente)
        REFERENCES clientes(id_pessoa)
        ON DELETE RESTRICT,
    CONSTRAINT ck_animais_sexo
        CHECK (sexo IN ('Macho', 'Fêmea', 'Outro'))
);

CREATE TABLE IF NOT EXISTS produtos (
    id_produto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(80) NOT NULL,
    marca VARCHAR(100) NOT NULL,
    descricao TEXT NOT NULL,
    valor_compra NUMERIC(10,2) NOT NULL,
    CONSTRAINT ck_produtos_valor
        CHECK (valor_compra >= 0)
);

CREATE TABLE IF NOT EXISTS servicos (
    id_servico BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    descricao TEXT,
    valor NUMERIC(10,2) NOT NULL,
    CONSTRAINT ck_servicos_valor
        CHECK (valor >= 0)
);

CREATE TABLE IF NOT EXISTS atendimentos (
    id_atendimento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_atendimento TIMESTAMP NOT NULL,
    id_atendente BIGINT NOT NULL,
    id_cliente BIGINT NOT NULL,
    id_animal BIGINT NOT NULL,
    id_veterinario BIGINT NOT NULL,
    descricao TEXT NOT NULL,
    CONSTRAINT fk_atendimentos_atendente
        FOREIGN KEY (id_atendente)
        REFERENCES atendentes(id_pessoa)
        ON DELETE RESTRICT,
    CONSTRAINT fk_atendimentos_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES clientes(id_pessoa)
        ON DELETE RESTRICT,
    CONSTRAINT fk_atendimentos_animal
        FOREIGN KEY (id_animal)
        REFERENCES animais(id_animal)
        ON DELETE RESTRICT,
    CONSTRAINT fk_atendimentos_veterinario
        FOREIGN KEY (id_veterinario)
        REFERENCES veterinarios(id_pessoa)
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS atendimento_itens (
    id_item BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_atendimento BIGINT NOT NULL,
    id_produto BIGINT,
    id_servico BIGINT,
    quantidade INTEGER NOT NULL DEFAULT 1,
    valor_unitario NUMERIC(10,2) NOT NULL,
    CONSTRAINT fk_itens_atendimento
        FOREIGN KEY (id_atendimento)
        REFERENCES atendimentos(id_atendimento)
        ON DELETE CASCADE,
    CONSTRAINT fk_itens_produto
        FOREIGN KEY (id_produto)
        REFERENCES produtos(id_produto)
        ON DELETE RESTRICT,
    CONSTRAINT fk_itens_servico
        FOREIGN KEY (id_servico)
        REFERENCES servicos(id_servico)
        ON DELETE RESTRICT,
    CONSTRAINT ck_itens_tipo
        CHECK (
            (id_produto IS NOT NULL AND id_servico IS NULL)
            OR
            (id_produto IS NULL AND id_servico IS NOT NULL)
        ),
    CONSTRAINT ck_itens_quantidade
        CHECK (quantidade > 0),
    CONSTRAINT ck_itens_valor
        CHECK (valor_unitario >= 0)
);
